/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

#if !defined(BROOKESIA_SERVICE_BLE_ENABLE_AUTO_REGISTER)
#   if defined(CONFIG_BROOKESIA_SERVICE_BLE_ENABLE_AUTO_REGISTER)
#       define BROOKESIA_SERVICE_BLE_ENABLE_AUTO_REGISTER  CONFIG_BROOKESIA_SERVICE_BLE_ENABLE_AUTO_REGISTER
#   else
#       define BROOKESIA_SERVICE_BLE_ENABLE_AUTO_REGISTER  (0)
#   endif
#endif

#if BROOKESIA_SERVICE_BLE_ENABLE_AUTO_REGISTER
#   if !defined(BROOKESIA_SERVICE_BLE_PLUGIN_SYMBOL)
#       define BROOKESIA_SERVICE_BLE_PLUGIN_SYMBOL  service_ble_symbol
#   endif
#endif

#define BROOKESIA_SERVICE_BLE_LOG_TAG  "SvcBLE"

#if !defined(BROOKESIA_SERVICE_BLE_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_SERVICE_BLE_ENABLE_DEBUG_LOG)
#       define BROOKESIA_SERVICE_BLE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_BLE_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_SERVICE_BLE_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if BROOKESIA_SERVICE_BLE_ENABLE_DEBUG_LOG
#   if !defined(BROOKESIA_SERVICE_BLE_SERVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_BLE_SERVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_BLE_SERVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_BLE_SERVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_BLE_SERVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#else
#   define BROOKESIA_SERVICE_BLE_SERVICE_ENABLE_DEBUG_LOG  (0)
#endif
