/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#define context_ impl_->context
#define http_binding_ impl_->http_binding
#define device_binding_ impl_->device_binding
#define storage_binding_ impl_->storage_binding
#define http_event_connections_ impl_->http_event_connections
#define primary_action_connection_ impl_->primary_action_connection
#define local_delete_action_connection_ impl_->local_delete_action_connection
#define entries_ impl_->entries
#define local_packages_ impl_->local_packages
#define installed_runtime_apps_ impl_->installed_runtime_apps
#define entry_paths_ impl_->entry_paths
#define visible_items_ impl_->visible_items
#define refresh_icon_indices_ impl_->refresh_icon_indices
#define startup_cache_candidates_ impl_->startup_cache_candidates
#define local_package_scan_dirs_ impl_->local_package_scan_dirs
#define local_package_scan_candidates_ impl_->local_package_scan_candidates
#define local_package_scan_results_ impl_->local_package_scan_results
#define pending_http_events_ impl_->pending_http_events
#define instance_to_entry_ impl_->instance_to_entry
#define local_package_by_manifest_id_ impl_->local_package_by_manifest_id
#define installed_manifest_ids_ impl_->installed_manifest_ids
#define installed_version_by_manifest_id_ impl_->installed_version_by_manifest_id
#define registered_icon_resource_ids_ impl_->registered_icon_resource_ids
#define local_package_scan_seen_keys_ impl_->local_package_scan_seen_keys
#define terminal_download_request_ids_ impl_->terminal_download_request_ids
#define applied_i18n_locale_ impl_->applied_i18n_locale
#define i18n_strings_ impl_->i18n_strings
#define status_text_ impl_->status_text
#define storage_text_ impl_->storage_text
#define refresh_dialog_message_ impl_->refresh_dialog_message
#define pending_delete_local_package_name_ impl_->pending_delete_local_package_name
#define pending_delete_success_package_name_ impl_->pending_delete_success_package_name
#define pending_delete_local_package_path_ impl_->pending_delete_local_package_path
#define pending_delete_success_package_path_ impl_->pending_delete_success_package_path
#define startup_cache_last_error_ impl_->startup_cache_last_error
#define view_mode_ impl_->view_mode
#define startup_load_phase_ impl_->startup_load_phase
#define local_package_scan_phase_ impl_->local_package_scan_phase
#define list_slot_count_ impl_->list_slot_count
#define list_page_ impl_->list_page
#define startup_cache_cursor_ impl_->startup_cache_cursor
#define local_package_scan_dir_cursor_ impl_->local_package_scan_dir_cursor
#define local_package_scan_candidate_cursor_ impl_->local_package_scan_candidate_cursor
#define message_dialog_request_id_ impl_->message_dialog_request_id
#define refresh_icon_timer_id_ impl_->refresh_icon_timer_id
#define size_metadata_timer_id_ impl_->size_metadata_timer_id
#define startup_load_timer_id_ impl_->startup_load_timer_id
#define view_mode_load_timer_id_ impl_->view_mode_load_timer_id
#define deferred_operation_timer_id_ impl_->deferred_operation_timer_id
#define local_package_scan_timer_id_ impl_->local_package_scan_timer_id
#define refresh_request_timeout_timer_id_ impl_->refresh_request_timeout_timer_id
#define refresh_result_timer_id_ impl_->refresh_result_timer_id
#define http_event_timer_id_ impl_->http_event_timer_id
#define time_sync_timeout_timer_id_ impl_->time_sync_timeout_timer_id
#define time_sync_success_close_timer_id_ impl_->time_sync_success_close_timer_id
#define http_general_state_ impl_->http_general_state
#define pending_view_mode_ impl_->pending_view_mode
#define pending_deferred_operations_ impl_->pending_deferred_operations
#define message_dialog_purpose_ impl_->message_dialog_purpose
#define pending_refresh_result_type_ impl_->pending_refresh_result_type
#define refresh_icon_purpose_ impl_->refresh_icon_purpose
#define pending_refresh_result_response_ impl_->pending_refresh_result_response
#define async_generation_ impl_->async_generation
#define storage_free_bytes_ impl_->storage_free_bytes
#define storage_capacity_known_ impl_->storage_capacity_known
#define refresh_request_id_ impl_->refresh_request_id
#define refresh_icon_request_id_ impl_->refresh_icon_request_id
#define download_dialog_request_id_ impl_->download_dialog_request_id
#define refresh_icon_cursor_ impl_->refresh_icon_cursor
#define refresh_in_progress_ impl_->refresh_in_progress
#define http_available_ impl_->http_available
#define device_available_ impl_->device_available
#define storage_available_ impl_->storage_available
#define network_ready_ impl_->network_ready
#define storage_match_warning_logged_ impl_->storage_match_warning_logged
#define time_sync_waiting_ impl_->time_sync_waiting
#define processing_pending_refresh_result_ impl_->processing_pending_refresh_result
#define startup_cache_load_in_progress_ impl_->startup_cache_load_in_progress
#define local_package_scan_in_progress_ impl_->local_package_scan_in_progress
#define local_package_scan_refresh_view_ impl_->local_package_scan_refresh_view
#define pending_http_events_mutex_ impl_->pending_http_events_mutex
